version: '3.9'

services:
  frontend:
    image: afdincendios-frontend:latest
    container_name: afdincendios-frontend
    restart: unless-stopped
    ports:
      - 4210:4200
    networks:
      - net-afd

networks:
  net-afd:
    driver: bridge