name: Deploy frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_NAME: afdincendios-frontend # Must be the same name of the git repository

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Create and run Docker container
        run: |
          export PATH=/opt/docker_cont/:$PATH && start_container.sh -p $PROJECT_NAME